_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 1
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.7
            "8":
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
architecture:
    value: AlexNet
batch_size:
    value: 64
dataset:
    value: CIFAR-10
epochs:
    value: 5
learning_rate:
    value: 0.001
momentum:
    value: 0.9
weight_decay:
    value: 0.005
